image: node:8.9.0

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"

stages:
  # - stage
  - production

# Deploy-to-Stage:
#   stage: stage
#   script:
#     - bash deploy/deploy.sh
#   rules:
#     - if: $CI_COMMIT_BRANCH == "dev"
#   environment:
#     name: staging

Deploy-to-Production:
  stage: production
  script:
    - bash deploy/deploy.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment:
    name: production
