module.exports = [
  { country: "Algeria", currency: "DZD" },
  { country: "Angola", currency: "AOA" },
  { country: "Benin", currency: "XOF" },
  { country: "Botswana", currency: "BWP" },
  { country: "Burundi", currency: "BIF" },
  { country: "Burkina Faso", currency: "XOF" },
  { country: "Cameroon", currency: "XAF" },
  { country: "Cape Verde", currency: "CVE" },
  { country: "Central African Republic", currency: "XAF" },
  { country: "Chad", currency: "XAF" },
  { country: "Comoros", currency: "KMF" },
  { country: "Cote d'Ivoire", currency: "XOF" },
  { country: "Congo - Kinshasa", currency: "CDF" },
  { country: "Djibouti", currency: "DJF" },
  { country: "Egypt", currency: "EGP" },
  { country: "Equatorial Guinea", currency: "XAF" },
  { country: "Eritrea", currency: "ERN" },
  { country: "Ethiopia", currency: "ETB" },
  { country: "Gabon", currency: "XAF" },
  { country: "Gambia", currency: "GMD" },
  { country: "Ghana", currency: "GHS" },
  { country: "Guinea", currency: "GNF" },
  { country: "Guinea-Bissau", currency: "GWP" },
  { country: "Kenya", currency: "KES" },
  { country: "Lesotho", currency: "LSL" },
  { country: "Liberia", currency: "LRD" },
  { country: "Libya", currency: "LYD" },
  { country: "Madagascar", currency: "MGA" },
  { country: "Malawi", currency: "MWK" },
  { country: "Mali", currency: "XOF" },
  { country: "Mauritania", currency: "MRO" },
  { country: "Mauritius", currency: "MUR" },
  { country: "Morocco", currency: "MAD" },
  { country: "Mozambique", currency: "MZN" },
  { country: "Namibia", currency: "NAD" },
  { country: "Niger", currency: "XOF" },
  { country: "Nigeria", currency: "NGN" },
  { country: "Congo - Brazzaville", currency: "XAF" },
  { country: "Rwanda", currency: "RWF" },
  { country: "Sao Tome and Principe", currency: "STD" },
  { country: "Senegal", currency: "XOF" },
  { country: "Seychelles", currency: "SCR" },
  { country: "Sierra Leone", currency: "SLL" },
  { country: "Somalia", currency: "SOS" },
  { country: "South Africa", currency: "ZAR" },
  { country: "South Sudan", currency: "SSP" },
  { country: "Sudan", currency: "SDG" },
  { country: "Eswatini", currency: "SZL" },
  { country: "Tanzania", currency: "TZS" },
  { country: "Togo", currency: "XOF" },
  { country: "Tunisia", currency: "TND" },
  { country: "Uganda", currency: "UGX" },
  { country: "Zambia", currency: "ZMW" },
  { country: "Zimbabwe", currency: "ZWD" },
];
