module.exports = [
  {
    country: "South Africa",
    country_code: "ZA",
    country_index: 85.03,
    region: "Southern Africa",
  },
  {
    country: "Kenya",
    country_code: "KE",
    country_index: 82.16,
    region: "Eastern Africa",
  },
  {
    country: "Egypt",
    country_code: "EG",
    country_index: 81.91,
    region: "Northern Africa",
  },
  {
    country: "Morocco",
    country_code: "MA",
    country_index: 81.6,
    region: "Northern Africa",
  },
  {
    country: "Tunisia",
    country_code: "TN",
    country_index: 78.66,
    region: "Northern Africa",
  },
  {
    country: "Namibia",
    country_code: "NA",
    country_index: 76.95,
    region: "Southern Africa",
  },
  {
    country: "Nigeria",
    country_code: "NG",
    country_index: 75.6,
    region: "Western Africa",
  },
  {
    country: "Ghana",
    country_code: "GH",
    country_index: 74.9,
    region: "Western Africa",
  },
  {
    country: "Mauritius",
    country_code: "MU",
    country_index: 73.43,
    region: "Eastern Africa",
  },
  {
    country: "Cote d'Ivoire",
    country_code: "CI",
    country_index: 72.91,
    region: "Western Africa",
  },
  {
    country: "Senegal",
    country_code: "SN",
    country_index: 71.45,
    region: "Western Africa",
  },
  {
    country: "Tanzania",
    country_code: "TZ",
    country_index: 71.09,
    region: "Eastern Africa",
  },
  {
    country: "Zambia",
    country_code: "ZM",
    country_index: 70.26,
    region: "Southern Africa",
  },
  {
    country: "Botswana",
    country_code: "BW",
    country_index: 69.22,
    region: "Southern Africa",
  },
  {
    country: "Eswatini",
    country_code: "SZ",
    country_index: 65.97,
    region: "Southern Africa",
  },
  {
    country: "Rwanda",
    country_code: "RW",
    country_index: 64.36,
    region: "Eastern Africa",
  },
  {
    country: "Uganda",
    country_code: "UG",
    country_index: 61.91,
    region: "Eastern Africa",
  },
  {
    country: "Madagascar",
    country_code: "MG",
    country_index: 59.05,
    region: "Eastern Africa",
  },
  {
    country: "Cameroon",
    country_code: "CM",
    country_index: 58.34,
    region: "Central Africa",
  },
  {
    country: "Zimbabwe",
    country_code: "ZW",
    country_index: 57.37,
    region: "Southern Africa",
  },
  {
    country: "Togo",
    country_code: "TG",
    country_index: 57.21,
    region: "Western Africa",
  },
  {
    country: "Algeria",
    country_code: "DZ",
    country_index: 55.2,
    region: "Northern Africa",
  },
  {
    country: "Ethiopia",
    country_code: "ET",
    country_index: 54.68,
    region: "Eastern Africa",
  },
  {
    country: "Mozambique",
    country_code: "MZ",
    country_index: 51.9,
    region: "Southern Africa",
  },
  {
    country: "Malawi",
    country_code: "MW",
    country_index: 51.05,
    region: "Southern Africa",
  },
  {
    country: "Congo - Brazzaville",
    country_code: "CG",
    country_index: 50.04,
    region: "Central Africa",
  },
  {
    country: "Angola",
    country_code: "AO",
    country_index: 49.11,
    region: "Southern Africa",
  },
  {
    country: "Burkina Faso",
    country_code: "BF",
    country_index: 48.86,
    region: "Western Africa",
  },
  {
    country: "Congo - Kinshasa",
    country_code: "CD",
    country_index: 48.11,
    region: "Central Africa",
  },
  {
    country: "Mali",
    country_code: "ML",
    country_index: 48.04,
    region: "Western Africa",
  },
  {
    country: "Benin",
    country_code: "BJ",
    country_index: 47.07,
    region: "Western Africa",
  },
  {
    country: "Lesotho",
    country_code: "LS",
    country_index: 45.23,
    region: "Southern Africa",
  },
  {
    country: "Sierra Leone",
    country_code: "SL",
    country_index: 43.34,
    region: "Western Africa",
  },
  {
    country: "Niger",
    country_code: "NE",
    country_index: 43.19,
    region: "Western Africa",
  },
  {
    country: "Gabon",
    country_code: "GA",
    country_index: 42.35,
    region: "Central Africa",
  },
  {
    country: "Guinea",
    country_code: "GN",
    country_index: 41.78,
    region: "Western Africa",
  },
  {
    country: "Burundi",
    country_code: "BI",
    country_index: 39.54,
    region: "Central Africa",
  },
  {
    country: "Seychelles",
    country_code: "SC",
    country_index: 37.35,
    region: "Eastern Africa",
  },
  {
    country: "Mauritania",
    country_code: "MR",
    country_index: 32.44,
    region: "Northern Africa",
  },
  {
    country: "Liberia",
    country_code: "LR",
    country_index: 28.59,
    region: "Western Africa",
  },
  {
    country: "Gambia",
    country_code: "GM",
    country_index: 28.41,
    region: "Western Africa",
  },
  {
    country: "Libya",
    country_code: "LY",
    country_index: 27.1,
    region: "Northern Africa",
  },
  {
    country: "Cape Verde",
    country_code: "CV",
    country_index: 26.32,
    region: "Western Africa",
  },
  {
    country: "Djibouti",
    country_code: "DJ",
    country_index: 23.96,
    region: "Eastern Africa",
  },
  {
    country: "Sao Tome and Principe",
    country_code: "ST",
    country_index: 22.1,
    region: "Central Africa",
  },
  {
    country: "Comoros",
    country_code: "KM",
    country_index: 20.43,
    region: "Eastern Africa",
  },
  {
    country: "Central African Republic",
    country_code: "CF",
    country_index: 20.38,
    region: "Central Africa",
  },
  {
    country: "Chad",
    country_code: "TD",
    country_index: 20.1,
    region: "Central Africa",
  },
  {
    country: "Equatorial Guinea",
    country_code: "GQ",
    country_index: 18.58,
    region: "Central Africa",
  },
  {
    country: "Guinea-Bissau",
    country_code: "GW",
    country_index: 11.79,
    region: "Western Africa",
  },
  {
    country: "Sudan",
    country_code: "SD",
    country_index: 0,
    region: "Eastern Africa",
  },
  {
    country: "Somalia",
    country_code: "SO",
    country_index: 0,
    region: "Eastern Africa",
  },
  {
    country: "South Sudan",
    country_code: "SS",
    country_index: 0,
    region: "Eastern Africa",
  },
];
